name: Zombies
main: org.soraworld.zombies.Zombies
version: 1.7.10-0.1.4
commands:
  zombie:
    description: "Zombies - https://github.com/Himmelt/Zombies"
    usage: "[Zombies] /zombie save|reload|allow|disallow|speed|health|radius|refresh|debug"
    permission: zombie
    permission-message: "[Zombies] You have no permission <zombie>"