name: Zombies
version: 1.7.10-1.1.1
author: Himmelt
main: org.soraworld.zombies.Zombies
depend: [Violet]
softdepend: []
website: https://github.com/Himmelt/Zombies
description: Zombies Plugin.

commands:
  zombie:
    description: "Zombies - https://github.com/Himmelt/Zombies"
    usage: "/zombie allow|disallow|speed|health|radius|refresh"
    permission: zombie.admin
    permission-message: "You have no permission <zombie.admin>"
permissions:
  zombie.admin:
    default: op
