name: Zombies
version: 1.2.0
author: Himmelt
main: org.soraworld.zombies.Zombies
depend: [Violet]
website: https://github.com/Himmelt/Zombies
description: Zombies Plugin.
permissions:
  zombies.admin:
    default: op
